import { Inter } from "next/font/google";

import "./globals.css";

import { AppContextProvider } from "@/providers/Context/AppContext";
import DarkmodeProvider from "@/providers/DarkModeProvider";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

// Metadata object containing information about the app
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout component serving as the main layout for the app
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`mx-10 mb-20 ${inter.className} dark:bg-black text-white`}
      >
        {/* Context provider for the app */}
        <AppContextProvider>
          {/* Provider for managing dark mode */}
          <DarkmodeProvider>
            {/* ToastContainer component for displaying toasts */}
            <ToastContainer />
            {/* Render the child components */}
            {children}
          </DarkmodeProvider>
        </AppContextProvider>
      </body>
    </html>
  );
}
